### ISSUE TITLE
Implement Networking Monitoring Functionality  

### ISSUE THREAD

**Issue by xororist** [xororist/shake-cli#2]
**Desired Features:**

**Network Information**: Retrieve basic information about the network data used by a PID, such as upload and download.
Real-time Monitoring: Implement functionality to continuously monitor networking operations.
Command Options: This implementation should be added to the current shake run command.

**Additional Considerations**:
Ensure that the network monitoring feature is non-intrusive and does not negatively impact system performance. Compatibility testing should be conducted across different operating systems, ensuring seamless functionality on Windows, macOS, and Linux.

**Expected Outcome**:
Upon completion, users should be able to use the shake run command to gather detailed information about the network usage of a PID.

**Comment by LyubomirT** [comment]
I think I can help with that, can you please assign this issue to me, if possible?

**Comment by xororist** [comment]
Yes of course, thank you for your reaching out! :)
I assigned you and created a branch corresponding to the issue from where you can start making your development!
Feel free to include any libraries as long are they still up to date and add them to the `pyproject.toml`
Don't hesitate if you have any questions!
